In [ ]:
import numpy as np

P = np.array([[0.1, 0.9]
            , [0.8, 0.2]])

### $P^K$ and Stationary(Steady State) distribution


In [4]:
epsilon = 0.00001
while(1):
    pai = P @ P
    if np.all(np.abs(pai - P) < epsilon):
        break
    P = pai

print(P)


[[0.47059408 0.52940592]
 [0.47058304 0.52941696]]


### Linear equation

$V = R + \lambda*P*V$

$(1-\lambda)*V = R$

Finally we got: $V = (1-\lambda)^-1 * R $




In [15]:
gamma = 0.9
P = np.array([
    [0.7,0.3],
    [0.9,0.1]
])
R = np.array([1,-1])
R = R.reshape(2,1)


# Bellman equation to solve this
I = np.eye(P.shape[0])
v = np.linalg.inv(I - gamma*P) @ R
print(v)


[[5.42372881]
 [3.72881356]]


### Value Iteration for sovling V*

1. Set $v_0 = [0, \ldots, 0]$
2. For $i = 0, 1, 2, \ldots$

   - For all states $s$, update

In [16]:
iterations = 10000
epsilon = 0.00001
v = np.zeros(2).reshape(2,1)


# Value iteration for find v*
for i in range(iterations):
    v_old = v.copy()
    v = R + gamma*np.dot(P,v_old)
    if np.all(np.abs(v - v_old) < epsilon):
        break
print(v)

[[5.42364168]
 [3.72872642]]


In [24]:
N = 3
S = N*N + 1
DONE = 2*N + 3
Target = 4
P = np.zeros((S,S))
for i in range(0,S):
    if i == DONE or i == Target:continue
    x = i%N
    y = i//N
    neighbors = []
    if x > 0:neighbors.append(i-1)
    if x < N-1:neighbors.append(i+1)
    if y > 0:neighbors.append(i-N)
    if y < N-1:neighbors.append(i+N)
    p = 1/len(neighbors)
    for j in neighbors:
        P[i,j] = p
    P[Target,DONE] = 1
    P[DONE,DONE] = 1

print(P)


[[0.         0.5        0.         0.5        0.         0.
  0.         0.         0.         0.        ]
 [0.33333333 0.         0.33333333 0.         0.33333333 0.
  0.         0.         0.         0.        ]
 [0.         0.5        0.         0.         0.         0.5
  0.         0.         0.         0.        ]
 [0.33333333 0.         0.         0.         0.33333333 0.
  0.33333333 0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         1.        ]
 [0.         0.         0.33333333 0.         0.33333333 0.
  0.         0.         0.33333333 0.        ]
 [0.         0.         0.         0.5        0.         0.
  0.         0.5        0.         0.        ]
 [0.         0.         0.         0.         0.33333333 0.
  0.33333333 0.         0.33333333 0.        ]
 [0.         0.         0.         0.         0.         0.5
  0.         0.5        0.         0.        ]
 [0.         0.         0.         