In [2]:
import numpy as np

P = np.array([[0.1, 0.9]
            , [0.8, 0.2]])

### $P^K$ and Stationary(Steady State) distribution


In [4]:
epsilon = 0.00001
while(1):
    pai = P @ P
    if np.all(np.abs(pai - P) < epsilon):
        break
    P = pai

print(P)


[[0.47059408 0.52940592]
 [0.47058304 0.52941696]]


### Linear equation

$V = R + \lambda*P*V$

$(1-\lambda)*V = R$

Finally we got: $V = (1-\lambda)^-1 * R $




In [15]:
gamma = 0.9
P = np.array([
    [0.7,0.3],
    [0.9,0.1]
])
R = np.array([1,-1])
R = R.reshape(2,1)


# Bellman equation to solve this
I = np.eye(P.shape[0])
v = np.linalg.inv(I - gamma*P) @ R
print(v)


[[5.42372881]
 [3.72881356]]


### Value Iteration for sovling V*

1. Set $v_0 = [0, \ldots, 0]$
2. For $i = 0, 1, 2, \ldots$

   - For all states $s$, update

In [16]:
iterations = 10000
epsilon = 0.00001
v = np.zeros(2).reshape(2,1)


# Value iteration for find v*
for i in range(iterations):
    v_old = v.copy()
    v = R + gamma*np.dot(P,v_old)
    if np.all(np.abs(v - v_old) < epsilon):
        break
print(v)

[[5.42364168]
 [3.72872642]]


In [8]:
def print_state(s):
    assert 0 <= s <= 9

    print("STATE", s)

    if s < 9:
        # normal state indicating y, x coordinates
        output = ['🪨' for _ in range(9)]
        output[4] = '🐟'
        output[s] = '🐱'
        for i in range(0, 9, 3):
            print(''.join(output[i:i+3]))
    else:
        print("DONE")

    print("")

## Value iteration for soving MDP

In [11]:
import numpy as np

P = np.array([
    [[0.5,0.5],
    [1,  0]]
    ,[[0,1],
    [0,1]
    ]
])
R = np.array([[5,-1],[10,2]]).T
v = np.zeros(2).reshape(2,1)

epsilon = 0.0001
iterations = 10000
gamma = 0.9

for i in range(iterations):
    new_v = v.copy()
    print(new_v)
    for a in range(0,2):
        for s in range (2):
            v[s] = R[s,a] + gamma*(P[a,s,s] @ v[s])
            print(f"v(i={i},a={a}):",v)
    # v = expected_return
    if np.all(np.abs(new_v - v) < epsilon):
        break


[[0.]
 [0.]]


ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)